name: Setup Action

description: Setup Project

runs:
  using: composite
  steps:
    - name: Setup node from `.nvmrc`
      uses: actions/setup-node@v2
      with:
        node-version-file: ".nvmrc"
    - name: Install dependancies using `pnpm`
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.24.3
        run_install: true
