name: Test Action

on: [push]
jobs:
  lint:
    name: Run code linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup repo
        uses: ./.github/actions/setup
      - name: Lint code
        run: pnpm lint

  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup repo
        uses: ./.github/actions/setup
      - name: Test code
        run: pnpm test
