name: Test Action
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup node from `.nvmrc`
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"
      - name: Install dependancies using `pnpm`
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.3
          run_install: true
      - name: Lint code
        run: pnpm lint
